defaults:
  - env: cloth_env_ARX
  - renderer: default_renderer
  - controller: ik
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

exp_root: log/experiments
timestamp: null  # whether to overwrite the timestamp

save_state: False
